Exceptions
==================

## Исключения

**Исключения** - это нештатная ситуация, ошибка во время выполнения программы.

## Типа исключений

**Контролируемые исключения** — контролируемое исключение представляет собой вид исключения, которое происходит на стадии компиляции, их также именуют исключениями периода компиляции. Обозначенные исключения не следует игнорировать в ходе компиляции, они требуют должного обращения (разрешения) со стороны программиста.

**Неконтролируемые исключения** — неконтролируемое исключение представляет собой исключение, которое происходит во время выполнения. Они также носят название исключения на этапе выполнения. Данная категория может включать погрешности программирования, такие как логические ошибки либо неверный способ использования API. Исключения на этапе выполнения игнорируются в ходе компиляции.


## Иерархия исключений

![](https://cloud.githubusercontent.com/assets/18701152/15581283/4c2f5348-2374-11e6-8fd2-e4de02d2c389.png)

Все классы исключений в Java представляют подтипы класса java.lang.Exception. Класс исключений является подклассом класса Throwable. Помимо класса исключений существует также подкласс ошибок, образовавшихся из класса Throwable.

Класс исключений делится на два основных подкласса: класс IOException и класс RuntimeException.

[Наиболее часто встречаемы исключения](http://proglang.su/java/exceptions-built-in-exceptions)

## Обработка исключений — try и catch

Блок try/catch размещается в начале и конце кода, который может сгенерировать исключение. Код в составе блока try/catch является защищенным кодом, синтаксис использования try/catch выглядит следующим образом:

```
try {
   // Защищенный код
}catch(НазваниеИсключения e1) {
   // Блок catch
}
```
### Многократные блоки catch

```
try {
   // Защищенный код
}catch(ИсключениеТип1 e1) {
   // Блок catch
}catch(ИсключениеТип2 e2) {
   // Блок catch
}catch(ИсключениеТип3 e3) {
   // Блок catch
}
```
### Перехват многотипных исключений
```
catch (IOException|FileNotFoundException ex) {
   logger.log(ex);
   throw ex;
```


### Ключевые слова throws/throw

Если метод может породить исключение, которое он сам не обрабатывает, он должен задать это поведение так, чтобы вызывающий его код мог позаботиться об этом исключении. Для этого к объявлению метода добавляется конструкция **throws**

Часть исключений может обрабатывать сама система. Но можно создать собственные исключения при помощи оператора **throw**. Код выглядит так:
``throw экземпляр_Throwable``

### Блок finally
В Java finally следует за блоком try либо блоком catch. Блок finally в коде выполняется всегда независимо от наличия исключения.

### Конструкция try-with-resources

В норме, при использовании различных видов ресурсов, таких как потоки, соединения и др., нам предстоит закрыть их непосредственно при использовании блока `finally`. В программе, представленной ниже, нами производится считывание данных из файла при использовании `FileReader`, после чего он закрывается блоком `finally`.
Пример:
```
try(FileReader fr = new FileReader("Путь к файлу")) {
   // использование ресурса
   }catch() {
      // тело catch 
   }
}
```

## Создание своих собственных исключений

Вы можете создать свои собственные исключения в среде Java. При записи собственных классов исключений следует принимать во внимание следующие аспекты:

+ Все исключения должны быть дочерними элементами Throwable.
+ Если вы планируете произвести запись контролируемого исключения с автоматическим использованием за счет правила обработки или объявления, вам следует расширить класс Exception.
+ Если вы хотите произвести запись исключения на этапе выполнения, вам следует расширить класс RuntimeException.
+ Вы можете определить собственный класс исключений, как показано ниже:

Пример:
```
// Название файла InsufficientFundsException.java
import java.io.*;

public class InsufficientFundsException extends Exception {
   private double amount;
   
   public InsufficientFundsException(double amount) {
      this.amount = amount;
   }
   
   public double getAmount() {
      return amount;
   }
}
```
